In [3]:

from pathlib import Path
import pandas as pd
import numpy as np

# Find the project folder automatically
PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_PATH = PROJECT_ROOT / "data" / "processed" / "expanded_model_dataset.csv"

# Load the existing dataset
df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("\nSeasons available:")
print(sorted(df["season"].unique()))

print("\nColumns:")
print(df.columns.tolist())

df.head()

Dataset loaded successfully!
Shape: (3458, 27)

Seasons available:
[np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

Columns:
['season', 'round', 'race_name', 'race_date', 'driver_id', 'driver_code', 'driver_number', 'driver_name', 'constructor_id', 'constructor_name', 'grid', 'position', 'position_text', 'points', 'laps', 'status', 'finish_time', 'fastest_lap_rank', 'fastest_lap_time', 'position_num', 'won_race', 'driver_prior_mean_finish', 'driver_prior_win_rate', 'driver_recent5_mean_finish', 'constructor_prior_mean_finish', 'constructor_prior_win_rate', 'starting_position_feature']

,season,round,race_name,race_date,driver_id,driver_code,driver_number,driver_name,constructor_id,constructor_name,...,fastest_lap_rank,fastest_lap_time,position_num,won_race,driver_prior_mean_finish,driver_prior_win_rate,driver_recent5_mean_finish,constructor_prior_mean_finish,constructor_prior_win_rate,starting_position_feature
0,2018,1,Australian Grand Prix,2018-03-25,alonso,ALO,14,Fernando Alonso,mclaren,McLaren,...,7.0,1:26.978,5,0,NaN,NaN,NaN,NaN,NaN,10.0
1,2018,1,Australian Grand Prix,2018-03-25,bottas,BOT,77,Valtteri Bottas,mercedes,Mercedes,...,8.0,1:27.019,8,0,NaN,NaN,NaN,NaN,NaN,15.0
2,2018,1,Australian Grand Prix,2018-03-25,brendon_hartley,HAR,28,Brendon Hartley,toro_rosso,Toro Rosso,...,13.0,1:28.176,15,0,NaN,NaN,NaN,NaN,NaN,16.0
3,2018,1,Australian Grand Prix,2018-03-25,ericsson,ERI,9,Marcus Ericsson,sauber,Sauber,...,19.0,1:32.210,19,0,NaN,NaN,NaN,NaN,NaN,17.0
4,2018,1,Australian Grand Prix,2018-03-25,gasly,GAS,10,Pierre Gasly,toro_rosso,Toro Rosso,...,18.0,1:30.649,18,0,NaN,NaN,NaN,NaN,NaN,20.0

In [8]:

# Step 1: Check the dataset before chronological validation

import pandas as pd
import numpy as np

# Confirm the data is available
print("Dataset shape:", historical_df.shape)

# Check which seasons are available
print("Seasons:", sorted(historical_df["season"].unique()))

# Check the number of races in each season
races_per_season = (
    historical_df.groupby("season")["race_name"]
    .nunique()
)

print("\nRaces per season:")
display(races_per_season.to_frame("number_of_races"))

# Check the target variable
print("\nWinner labels:")
display(historical_df["won_race"].value_counts(dropna=False))

# Check missing values in our intended features
candidate_features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

print("\nMissing values in candidate features:")
display(
    historical_df[candidate_features]
    .isna()
    .sum()
    .to_frame("missing_values")
)

print("\nPre-validation checks completed.")

Dataset shape: (3458, 27)
Seasons: [np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

Races per season:

        number_of_races
season
2018                 21
2019                 21
2020                 17
2021                 22
2022                 22
2023                 22
2024                 24
2025                 24

Winner labels:

won_race
0    3285
1     173
Name: count, dtype: int64

Missing values in candidate features:

                               missing_values
starting_position_feature                  45
driver_prior_mean_finish                   43
driver_prior_win_rate                      43
driver_recent5_mean_finish                 43
constructor_prior_mean_finish              32
constructor_prior_win_rate                 32

Pre-validation checks completed.

In [5]:

# Display variables currently available in the notebook
%whos DataFrame

Variable   Type         Data/Info
---------------------------------
df         DataFrame    Shape: (3458, 27)

In [7]:

historical_df = df

print("Dataset shape:", historical_df.shape)
print("Seasons:", sorted(historical_df["season"].unique()))

Dataset shape: (3458, 27)
Seasons: [np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

In [9]:

# Step 2: Define features and chronological validation seasons

from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier

features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

target = "won_race"

validation_splits = [
    (2021, 2022),
    (2022, 2023),
    (2023, 2024),
]

# Keep only rows with a known target and usable race identity
data = historical_df.dropna(
    subset=[target, "season", "round", "race_name"]
).copy()

data[target] = data[target].astype(int)

print("Features:", features)
print("Target:", target)
print("Validation splits:", validation_splits)
print("Rows available:", len(data))
print("Target classes:")
print(data[target].value_counts().sort_index())

Features: ['starting_position_feature', 'driver_prior_mean_finish', 'driver_prior_win_rate', 'driver_recent5_mean_finish', 'constructor_prior_mean_finish', 'constructor_prior_win_rate']
Target: won_race
Validation splits: [(2021, 2022), (2022, 2023), (2023, 2024)]
Rows available: 3458
Target classes:
won_race
0    3285
1     173
Name: count, dtype: int64

In [10]:

# Step 3: Chronological model validation

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import log_loss, brier_score_loss

results = []

# Baseline: starting position only
baseline_features = ["starting_position_feature"]

# Compare baseline, Logistic Regression, and Random Forest
for train_end, test_season in validation_splits:

    train = data[data["season"] <= train_end].copy()
    test = data[data["season"] == test_season].copy()

    print(f"\nValidating season {test_season}")
    print(f"Training rows: {len(train)}")
    print(f"Testing rows: {len(test)}")

    if train.empty or test.empty:
        print("Skipping: training or test data is empty.")
        continue

    # Ensure feature values are numeric and infinite values are missing
    for col in features:
        train[col] = pd.to_numeric(train[col], errors="coerce")
        test[col] = pd.to_numeric(test[col], errors="coerce")

    train[features] = train[features].replace([np.inf, -np.inf], np.nan)
    test[features] = test[features].replace([np.inf, -np.inf], np.nan)

    models = {
        "Baseline": (
            baseline_features,
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                ("model", LogisticRegression(max_iter=2000))
            ])
        ),
        "Logistic Regression": (
            features,
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                ("model", LogisticRegression(max_iter=2000))
            ])
        ),
        "Random Forest": (
            features,
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("model", RandomForestClassifier(
                    n_estimators=300,
                    min_samples_leaf=3,
                    random_state=42,
                    n_jobs=-1
                ))
            ])
        )
    }

    for model_name, (model_features, pipeline) in models.items():

        X_train = train[model_features]
        y_train = train[target]
        X_test = test[model_features]
        y_test = test[target]

        # Train only on seasons before the test season
        pipeline.fit(X_train, y_train)

        # Probability that each driver wins
        probabilities = pipeline.predict_proba(X_test)[:, 1]

        # Binary probability metrics across driver-race records
        ll = log_loss(y_test, probabilities, labels=[0, 1])
        brier = brier_score_loss(y_test, probabilities)

        # Top-1 winner accuracy, evaluated race by race.
        # Only include races with exactly one recorded winner.
        evaluation = test[
            ["season", "round", "race_name", target]
        ].copy()

        evaluation["predicted_probability"] = probabilities

        race_winners = evaluation.groupby(
            ["season", "round"], sort=False
        )[target].sum()

        valid_races = race_winners[race_winners == 1].index

        valid_evaluation = evaluation.set_index(
            ["season", "round"]
        ).loc[
            evaluation.set_index(["season", "round"]).index.isin(
                valid_races
            )
        ].reset_index()

        if len(valid_races) > 0:
            top_predictions = valid_evaluation.loc[
                valid_evaluation.groupby(
                    ["season", "round"]
                )["predicted_probability"].idxmax()
            ]

            winner_accuracy = top_predictions[target].mean()
        else:
            winner_accuracy = np.nan

        results.append({
            "test_season": test_season,
            "model": model_name,
            "training_rows": len(train),
            "test_rows": len(test),
            "races_with_one_recorded_winner": len(valid_races),
            "top1_winner_accuracy": winner_accuracy,
            "log_loss": ll,
            "brier_score": brier
        })

# Display results
results_df = pd.DataFrame(results)

if not results_df.empty:
    results_df = results_df.sort_values(
        ["test_season", "log_loss"]
    ).reset_index(drop=True)

    print("\nCHRONOLOGICAL VALIDATION RESULTS")
    display(results_df.round(4))
else:
    print("No results generated. Check the season split and dataset.")

Validating season 2022
Training rows: 1620
Testing rows: 440

Validating season 2023
Training rows: 2060
Testing rows: 440

Validating season 2024
Training rows: 2500
Testing rows: 479

CHRONOLOGICAL VALIDATION RESULTS

,test_season,model,training_rows,test_rows,races_with_one_recorded_winner,top1_winner_accuracy,log_loss,brier_score
0,2022,Logistic Regression,1620,440,22,0.4545,0.1247,0.0363
1,2022,Baseline,1620,440,22,0.4545,0.1390,0.0367
2,2022,Random Forest,1620,440,22,0.0000,0.1391,0.0456
3,2023,Random Forest,2060,440,22,0.7273,0.0710,0.0194
4,2023,Logistic Regression,2060,440,22,0.7273,0.0793,0.0225
5,2023,Baseline,2060,440,22,0.6364,0.1173,0.0334
6,2024,Logistic Regression,2500,479,24,0.5417,0.1191,0.0346
7,2024,Random Forest,2500,479,24,0.4167,0.1199,0.0347
8,2024,Baseline,2500,479,24,0.4583,0.1287,0.0354

In [11]:

# Step 4: Race-level probability evaluation

race_results = []

for train_end, test_season in validation_splits:

    train = data[data["season"] <= train_end].copy()
    test = data[data["season"] == test_season].copy()

    # Convert feature values to numeric and handle infinities
    for col in features:
        train[col] = pd.to_numeric(train[col], errors="coerce")
        test[col] = pd.to_numeric(test[col], errors="coerce")

    train[features] = train[features].replace(
        [np.inf, -np.inf], np.nan
    )
    test[features] = test[features].replace(
        [np.inf, -np.inf], np.nan
    )

    models = {
        "Baseline": (
            ["starting_position_feature"],
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                ("model", LogisticRegression(max_iter=2000))
            ])
        ),
        "Logistic Regression": (
            features,
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                ("model", LogisticRegression(max_iter=2000))
            ])
        ),
        "Random Forest": (
            features,
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("model", RandomForestClassifier(
                    n_estimators=300,
                    min_samples_leaf=3,
                    random_state=42,
                    n_jobs=-1
                ))
            ])
        )
    }

    # Evaluate only races with exactly one recorded winner
    valid_races = []

    for race_key, race in test.groupby(
        ["season", "round"], sort=True
    ):
        if race[target].sum() == 1:
            valid_races.append((race_key, race))

    for model_name, (model_features, model) in models.items():

        model.fit(train[model_features], train[target])

        raw_probabilities = model.predict_proba(
            test[model_features]
        )[:, 1]

        scored_test = test[
            ["season", "round", target]
        ].copy()

        scored_test["raw_probability"] = raw_probabilities

        top1_correct = []
        winner_log_losses = []
        multiclass_briers = []

        for race_key, race in valid_races:

            race_scores = scored_test[
                (scored_test["season"] == race_key[0]) &
                (scored_test["round"] == race_key[1])
            ].copy()

            raw = race_scores["raw_probability"].to_numpy()
            total = raw.sum()

            # Convert scores to probabilities summing to 1 per race
            if total > 0:
                probabilities = raw / total
            else:
                probabilities = np.full(
                    len(raw), 1 / len(raw)
                )

            actual = race_scores[target].to_numpy()

            predicted_winner = np.argmax(probabilities)

            top1_correct.append(
                int(actual[predicted_winner] == 1)
            )

            winner_probability = probabilities[actual == 1][0]

            winner_log_losses.append(
                -np.log(np.clip(winner_probability, 1e-15, 1.0))
            )

            multiclass_briers.append(
                np.sum((probabilities - actual) ** 2)
            )

        race_results.append({
            "test_season": test_season,
            "model": model_name,
            "races_evaluated": len(valid_races),
            "top1_winner_accuracy": np.mean(top1_correct),
            "mean_winner_log_loss": np.mean(winner_log_losses),
            "mean_multiclass_brier": np.mean(multiclass_briers)
        })

race_level_df = pd.DataFrame(race_results)

display(
    race_level_df.sort_values(
        ["test_season", "mean_winner_log_loss"]
    ).reset_index(drop=True).round(4)
)

,test_season,model,races_evaluated,top1_winner_accuracy,mean_winner_log_loss,mean_multiclass_brier
0,2022,Logistic Regression,22,0.4545,1.6013,0.7134
1,2022,Random Forest,22,0.0000,1.7791,0.8946
2,2022,Baseline,22,0.4545,1.9334,0.7344
3,2023,Random Forest,22,0.7273,0.8623,0.4037
4,2023,Logistic Regression,22,0.7273,0.9289,0.4267
5,2023,Baseline,22,0.6364,1.5440,0.6687
6,2024,Logistic Regression,24,0.5417,1.5460,0.6802
7,2024,Random Forest,24,0.4167,1.5589,0.6837
8,2024,Baseline,24,0.4583,1.7384,0.7062

In [12]:

# Step 5: Audit feature availability and missing values

feature_columns = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

print("Rows per season:")
display(
    historical_df.groupby("season").size().to_frame("rows")
)

print("\nMissing values by feature and season:")
display(
    historical_df.groupby("season")[feature_columns]
    .apply(lambda frame: frame.isna().sum())
)

print("\nCheck winner count per race:")
winner_counts = historical_df.groupby(
    ["season", "round", "race_name"]
)["won_race"].sum()

display(winner_counts.value_counts().sort_index().to_frame("race_count"))

print("\nFeature audit completed.")

Rows per season:

        rows
season
2018     420
2019     420
2020     340
2021     440
2022     440
2023     440
2024     479
2025     479

Missing values by feature and season:

,starting_position_feature,driver_prior_mean_finish,driver_prior_win_rate,driver_recent5_mean_finish,constructor_prior_mean_finish,constructor_prior_win_rate
season,,,,,,
2018,1,20,20,20,20,20
2019,12,6,6,6,4,4
2020,5,3,3,3,2,2
2021,12,3,3,3,4,4
2022,11,2,2,2,0,0
2023,3,3,3,3,0,0
2024,1,3,3,3,2,2
2025,0,3,3,3,0,0

Check winner count per race:

          race_count
won_race
1                173

Feature audit completed.

In [14]:

import json
from pathlib import Path

# Define the project path independently
PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)

notebooks_dir = PROJECT_DIR / "notebooks"

search_terms = [
    "starting_position_feature",
    "expanded_model_dataset.csv",
]

if not notebooks_dir.exists():
    print("Notebook folder not found:", notebooks_dir)
else:
    for notebook_path in notebooks_dir.glob("*.ipynb"):
        with open(notebook_path, "r", encoding="utf-8") as file:
            notebook = json.load(file)

        for cell_number, cell in enumerate(notebook.get("cells", [])):
            source = "".join(cell.get("source", []))

            if any(term in source for term in search_terms):
                print("\n" + "=" * 70)
                print("Notebook:", notebook_path.name)
                print("Cell:", cell_number)
                print(source[:4000])

======================================================================
Notebook: 01_data_collection.ipynb
Cell: 0

from pathlib import Path
import pandas as pd
import joblib

# Project paths
PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)

DATA_PATH = (
    PROJECT_DIR / "data" / "processed"
    / "expanded_model_dataset.csv"
)

MODEL_DIR = PROJECT_DIR / "models"
REPORT_DIR = PROJECT_DIR / "reports"

# Load the saved dataset
expanded_df = pd.read_csv(DATA_PATH)

# Restore the feature list
expanded_features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

target = "won_race"

# Restore the saved models
baseline_model = joblib.load(
    MODEL_DIR / "baseline_model.joblib"
)

enhanced_model = joblib.load(
    MODEL_DIR / "logistic_regression_model.joblib"
)

rf_model = joblib.load(
    MODEL_DIR / "random_forest_model.joblib"
)

print("Project restored successfully")
print("Dataset shape:", expanded_df.shape)
print("Seasons:", sorted(expanded_df["season"].unique()))
print("Models: Baseline, Logistic Regression, Random Forest")


======================================================================
Notebook: 01_data_collection.ipynb
Cell: 49

# Build a larger, chronological model dataset

expanded_df = history[
    history["season"].between(2018, 2025)
].copy()

expanded_df["starting_position_feature"] = pd.to_numeric(
    expanded_df["grid"], errors="coerce"
)

# Keep only rows with a known starting position
expanded_df = expanded_df[
    expanded_df["starting_position_feature"].notna()
].copy()

# Define the new, consistent feature sets
grid_baseline_features = ["starting_position_feature"]

expanded_features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate"
]

# Chronological split
expanded_train = expanded_df[
    expanded_df["season"].between(2018, 2024)
].copy()

expanded_test = expanded_df[
    expanded_df["season"] == 2025
].copy()

print("Expanded training rows:", len(expanded_train))
print("2025 test rows:", len(expanded_test))
print("Training seasons:",
      sorted(expanded_train["season"].unique()))
print("Testing seasons:",
      sorted(expanded_test["season"].unique()))

# Check race-level target integrity
winner_audit = (
    expanded_df.groupby(["season", "round"])["won_race"]
    .sum()
)

print("\nTotal races:", len(winner_audit))
print("Races with exactly one winner:",
      int((winner_audit == 1).sum()))
print("Races with invalid winner counts:",
      int((winner_audit != 1).sum()))

print("\nRows by season:")
display(
    expanded_df.groupby("season").agg(
        driver_records=("driver_id", "size"),
        races=("round", "nunique"),
        winners=("won_race", "sum"),
        missing_grid=("starting_position_feature",
                      lambda s: s.isna().sum())
    ).reset_index()
)


======================================================================
Notebook: 01_data_collection.ipynb
Cell: 50

from pathlib import Path

PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)

# Check likely locations for the historical dataset
candidates = [
    PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv",
    PROJECT_DIR / "data" / "processed" / "history.csv",
    PROJECT_DIR / "data" / "history.csv",
]

for path in candidates:
    print(f"{'FOUND' if path.exists() else 'NOT FOUND'}: {path}")


======================================================================
Notebook: 01_data_collection.ipynb
Cell: 51

import pandas as pd

history_path = (
    PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv"
)

history = pd.read_csv(history_path)

print("History restored:", history.shape)
print("Columns:", history.columns.tolist())
print("Seasons:", sorted(history["season"].dropna().unique()))


======================================================================
Notebook: 01_data_collection.ipynb
Cell: 52

import pandas as pd
from pathlib import Path

PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)

dataset_path = (
    PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv"
)

expanded_df = pd.read_csv(dataset_path)

print("Dataset loaded successfully")
print("Shape:", expanded_df.shape)

print("\nColumns:")
print(expanded_df.columns.tolist())

print("\nSeasons available:")
print(sorted(expanded_df["season"].dropna().unique()))

print("\nRequired-column audit:")
required_columns = [
    "season",
    "round",
    "driver_id",
    "won_race",
    "grid",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

for column in required_columns:
    status = "FOUND" if column in expanded_df.columns else "MISSING"
    print(f"{status}: {column}")

if "grid" in expanded_df.columns:
    print("\nGrid missing values:", expanded_df["grid"].isna().sum())

if {"season", "round", "won_race"}.issubset(expanded_df.columns):
    winner_audit = expanded_df.groupby(["season", "round"])["won_race"].sum()
    print("\nRace groups:", len(winner_audit))
    print("Groups with exactly one winner:", int((winner_audit == 1).sum()))
    print("Groups with invalid winner counts:", int((winner_audit != 1).sum()))

print("\nRows by season:")
if "season" in expanded_df.columns:
    print(expanded_df.groupby("season").size().to_string())


======================================================================
Notebook: 01_data_collection.ipynb
Cell: 53

# Create the chronological train/test split

expanded_features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

target = "won_race"

# Training data: 2018–2024
expanded_train = expanded_df[
    expanded_df["season"].between(2018, 2024)
].copy()

# Unseen test data: 2025
expanded_test = expanded_df[
    expanded_df["season"] == 2025
].copy()

print("Training shape:", expanded_train.shape)
print("Testing shape:", expanded_test.shape)

print("\nTraining seasons:",
      sorted(expanded_train["season"].unique()))

print("Testing seasons:",
      sorted(expanded_test["season"].unique()))

print("\nTraining rows by season:")
print(expanded_train.groupby("season").size().to_string())

print("\nTest rows by season:")
print(expanded_test.groupby("season").size().to_string())

# Validate features and target
assert all(c in expanded_df.columns for c in expanded_features)
assert expanded_train[target].notna().all()
assert expanded_test[target].notna().all()
assert expanded_train["season"].max() < expanded_test["season"].min()

print("\nChronological split created successfully.")


======================================================================
Notebook: 01_data_collection.ipynb
Cell: 61


# Read-only audit: inspect starting-position values by season
position_audit = (
    expanded_df.groupby("season")
    .agg(
        rows=("starting_position_feature", "size"),
        missing_positions=("starting_position_feature",
                           lambda s: s.isna().sum()),
        unique_positions=("starting_position_feature",
                          "nunique"),
        minimum_position=("starting_position_feature", "min"),
        maximum_position=("starting_position_feature", "max"),
    )
    .reset_index()
)

display(position_audit)

# Compare the feature against the raw grid column, if available
if "grid" in expanded_df.columns:
    print(
        "Feature equals grid:",
        expanded_df["starting_position_feature"]
        .equals(expanded_df["grid"])
    )
    display(
        expanded_df[
            ["season", "round", "driver_name",
             "grid", "starting_position_feature"]
        ].head(10)
    )
else:
    print("No raw 'grid' column exists in expanded_df.")


======================================================================
Notebook: 02_model_recovery_fixed.ipynb
Cell: 1
from pathlib import Path
import warnings
import joblib
import numpy as np
import pandas as pd

from IPython.display import display
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

PROJECT_DIR = Path(r"C:\Users\saksham\Desktop\Project\f1-prediction-platform")
DATA_PATH = PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv"
MODEL_DIR = PROJECT_DIR / "models"
REPORT_DIR = PROJECT_DIR / "reports"

MODEL_DIR.mkdir(parents=True, exist_ok=True)
REPORT_DIR.mkdir(parents=True, exist_ok=True)

print("Project folder exists:", PROJECT_DIR.exists())
print("Dataset exists:", DATA_PATH.exists())
print("Dataset path:", DATA_PATH)
print("Models folder:", MODEL_DIR)
print("Reports folder:", REPORT_DIR)

if not PROJECT_DIR.exists():
    raise FileNotFoundError(
        "Project folder was not found. Update PROJECT_DIR to your actual project path."
    )

if not DATA_PATH.exists():
    raise FileNotFoundError(
        "expanded_model_dataset.csv was not found. Do not recollect data yet; "
        "check the project's data/processed folder."
    )


======================================================================
Notebook: 02_model_recovery_fixed.ipynb
Cell: 2
# Load the saved historical dataset
expanded_df = pd.read_csv(DATA_PATH)

expanded_features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]
baseline_features = ["starting_position_feature"]
target = "won_race"

required_columns = [
    "season", "round", "race_name", "driver_name", "driver_id",
    "constructor_name", target, *expanded_features
]
missing_columns = [col for col in required_columns if col not in expanded_df.columns]

print("Dataset shape:", expanded_df.shape)
print("Seasons:", sorted(expanded_df["season"].dropna().astype(int).unique()))
print("Missing required columns:", missing_columns)

if missing_columns:
    raise ValueError(
        "The saved dataset is missing required columns. "
        "Share this list before running further cells."
    )

expanded_df["season"] = pd.to_numeric(expanded_df["season"], errors="coerce")
expanded_df[target] = pd.to_numeric(expanded_df[target], errors="coerce")

expanded_train = expanded_df[expanded_df["season"].between(2018, 2024)].copy()
expanded_test = expanded_df[expanded_df["season"] == 2025].copy()

if expanded_train.empty or expanded_test.empty:
    raise ValueError("Expected training seasons 2018–2024 and test season 2025.")

print("Training rows:", len(expanded_train))
print("Test rows:", len(expanded_test))
print("Training seasons:", sorted(expanded_train["season"].unique()))
print("Test seasons:", sorted(expanded_test["season"].unique()))

winner_counts = expanded_test.groupby(["season", "round"])[target].sum()
print("2025 races:", len(winner_counts))
print("Races with exactly one winner:", int((winner_counts == 1).sum()))
print("Races with invalid winner counts:", int((winner_counts != 1).sum()))

if not (winner_counts == 1).all():
    raise ValueError("At least one 2025 race does not have exactly one winner.")


======================================================================
Notebook: 02_model_recovery_fixed.ipynb
Cell: 4
# Rebuild the 2025 driver-level predictions and race rankings
test_predictions = expanded_test[
    [
        "season", "round", "race_name", "driver_id", "driver_name",
        "constructor_name", "grid", "starting_position_feature", target
    ]
].copy()

test_predictions["baseline_score"] = baseline_model.predict_proba(
    X_test_baseline
)[:, 1]

test_predictions["logistic_score"] = logistic_history_model.predict_proba(
    X_test_history
)[:, 1]

test_predictions["random_forest_score"] = random_forest_model.predict_proba(
    X_test_history
)[:, 1]

for score_col, rank_col in [
    ("baseline_score", "baseline_rank"),
    ("logistic_score", "logistic_rank"),
    ("random_forest_score", "rf_rank"),
]:
    test_predictions[rank_col] = (
        test_predictions.groupby(["season", "round"])[score_col]
        .rank(method="first", ascending=False)
        .astype(int)
    )

def summarize_rankings(df, rank_col, model_name):
    winners = df[df[target] == 1]
    return {
        "model": model_name,
        "races_evaluated": winners[["season", "round"]].drop_duplicates().shape[0],
        "top1_correct": int((winners[rank_col] == 1).sum()),
        "top1_accuracy_pct": round((winners[rank_col] == 1).mean() * 100, 2),
        "winner_in_top3_pct": round((winners[rank_col] <= 3).mean() * 100, 2),
        "mean_actual_winner_rank": round(winners[rank_col].mean(), 2),
    }

model_comparison = pd.DataFrame([
    summarize_rankings(test_predictions, "baseline_rank", "Starting-grid baseline"),
    summarize_rankings(test_predictions, "logistic_rank", "Logistic Regression + history"),
    summarize_rankings(test_predictions, "rf_rank", "Random Forest + history"),
])

display(model_comparison)

prediction_path = REPORT_DIR / "predictions_2025_rebuilt.csv"
comparison_path = REPORT_DIR / "model_comparison_2025_rebuilt.csv"
test_predictions.to_csv(prediction_path, index=False)
model_comparison.to_csv(comparison_path, index=False)

print("Saved predictions:", prediction_path)
print("Saved model comparison:", comparison_path)


======================================================================
Notebook: 03_chronological_validation.ipynb
Cell: 0

from pathlib import Path
import pandas as pd
import numpy as np

# Find the project folder automatically
PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_PATH = PROJECT_ROOT / "data" / "processed" / "expanded_model_dataset.csv"

# Load the existing dataset
df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("\nSeasons available:")
print(sorted(df["season"].unique()))

print("\nColumns:")
print(df.columns.tolist())

df.head()


======================================================================
Notebook: 03_chronological_validation.ipynb
Cell: 1

# Step 1: Check the dataset before chronological validation

import pandas as pd
import numpy as np

# Confirm the data is available
print("Dataset shape:", historical_df.shape)

# Check which seasons are available
print("Seasons:", sorted(historical_df["season"].unique()))

# Check the number of races in each season
races_per_season = (
    historical_df.groupby("season")["race_name"]
    .nunique()
)

print("\nRaces per season:")
display(races_per_season.to_frame("number_of_races"))

# Check the target variable
print("\nWinner labels:")
display(historical_df["won_race"].value_counts(dropna=False))

# Check missing values in our intended features
candidate_features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

print("\nMissing values in candidate features:")
display(
    historical_df[candidate_features]
    .isna()
    .sum()
    .to_frame("missing_values")
)

print("\nPre-validation checks completed.")


======================================================================
Notebook: 03_chronological_validation.ipynb
Cell: 4

# Step 2: Define features and chronological validation seasons

from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier

features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

target = "won_race"

validation_splits = [
    (2021, 2022),
    (2022, 2023),
    (2023, 2024),
]

# Keep only rows with a known target and usable race identity
data = historical_df.dropna(
    subset=[target, "season", "round", "race_name"]
).copy()

data[target] = data[target].astype(int)

print("Features:", features)
print("Target:", target)
print("Validation splits:", validation_splits)
print("Rows available:", len(data))
print("Target classes:")
print(data[target].value_counts().sort_index())


======================================================================
Notebook: 03_chronological_validation.ipynb
Cell: 5

# Step 3: Chronological model validation

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import log_loss, brier_score_loss

results = []

# Baseline: starting position only
baseline_features = ["starting_position_feature"]

# Compare baseline, Logistic Regression, and Random Forest
for train_end, test_season in validation_splits:

    train = data[data["season"] <= train_end].copy()
    test = data[data["season"] == test_season].copy()

    print(f"\nValidating season {test_season}")
    print(f"Training rows: {len(train)}")
    print(f"Testing rows: {len(test)}")

    if train.empty or test.empty:
        print("Skipping: training or test data is empty.")
        continue

    # Ensure feature values are numeric and infinite values are missing
    for col in features:
        train[col] = pd.to_numeric(train[col], errors="coerce")
        test[col] = pd.to_numeric(test[col], errors="coerce")

    train[features] = train[features].replace([np.inf, -np.inf], np.nan)
    test[features] = test[features].replace([np.inf, -np.inf], np.nan)

    models = {
        "Baseline": (
            baseline_features,
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                ("model", LogisticRegression(max_iter=2000))
            ])
        ),
        "Logistic Regression": (
            features,
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                ("model", LogisticRegression(max_iter=2000))
            ])
        ),
        "Random Forest": (
            features,
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("model", RandomForestClassifier(
                    n_estimators=300,
                    min_samples_leaf=3,
                    random_state=42,
                    n_jobs=-1
                ))
            ])
        )
    }

    for model_name, (model_features, pipeline) in models.items():

        X_train = train[model_features]
        y_train = train[target]
        X_test = test[model_features]
        y_test = test[target]

        # Train only on seasons before the test season
        pipeline.fit(X_train, y_train)

        # Probability that each driver wins
        probabilities = pipeline.predict_proba(X_test)[:, 1]

        # Binary probability metrics across driver-race records
        ll = log_loss(y_test, probabilities, labels=[0, 1])
        brier = brier_score_loss(y_test, probabilities)

        # Top-1 winner accuracy, evaluated race by race.
        # Only include races with exactly one recorded winner.
        evaluation = test[
            ["season", "round", "race_name", target]
        ].copy()


In [15]:

import json
from pathlib import Path

PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)

for notebook_name in [
    "01_data_collection.ipynb",
    "recovery.ipynb",
]:
    notebook_path = PROJECT_DIR / "notebooks" / notebook_name

    if not notebook_path.exists():
        continue

    with open(notebook_path, "r", encoding="utf-8") as file:
        notebook = json.load(file)

    for i, cell in enumerate(notebook.get("cells", [])):
        source = "".join(cell.get("source", []))

        if (
            "starting_position_feature" in source
            or "expanded_model_dataset.csv" in source
        ):
            print(f"\n{'=' * 60}")
            print(f"{notebook_name} — Cell {i}")
            print(source[:2500])

============================================================
01_data_collection.ipynb — Cell 0

from pathlib import Path
import pandas as pd
import joblib

# Project paths
PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)

DATA_PATH = (
    PROJECT_DIR / "data" / "processed"
    / "expanded_model_dataset.csv"
)

MODEL_DIR = PROJECT_DIR / "models"
REPORT_DIR = PROJECT_DIR / "reports"

# Load the saved dataset
expanded_df = pd.read_csv(DATA_PATH)

# Restore the feature list
expanded_features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

target = "won_race"

# Restore the saved models
baseline_model = joblib.load(
    MODEL_DIR / "baseline_model.joblib"
)

enhanced_model = joblib.load(
    MODEL_DIR / "logistic_regression_model.joblib"
)

rf_model = joblib.load(
    MODEL_DIR / "random_forest_model.joblib"
)

print("Project restored successfully")
print("Dataset shape:", expanded_df.shape)
print("Seasons:", sorted(expanded_df["season"].unique()))
print("Models: Baseline, Logistic Regression, Random Forest")


============================================================
01_data_collection.ipynb — Cell 49

# Build a larger, chronological model dataset

expanded_df = history[
    history["season"].between(2018, 2025)
].copy()

expanded_df["starting_position_feature"] = pd.to_numeric(
    expanded_df["grid"], errors="coerce"
)

# Keep only rows with a known starting position
expanded_df = expanded_df[
    expanded_df["starting_position_feature"].notna()
].copy()

# Define the new, consistent feature sets
grid_baseline_features = ["starting_position_feature"]

expanded_features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate"
]

# Chronological split
expanded_train = expanded_df[
    expanded_df["season"].between(2018, 2024)
].copy()

expanded_test = expanded_df[
    expanded_df["season"] == 2025
].copy()

print("Expanded training rows:", len(expanded_train))
print("2025 test rows:", len(expanded_test))
print("Training seasons:",
      sorted(expanded_train["season"].unique()))
print("Testing seasons:",
      sorted(expanded_test["season"].unique()))

# Check race-level target integrity
winner_audit = (
    expanded_df.groupby(["season", "round"])["won_race"]
    .sum()
)

print("\nTotal races:", len(winner_audit))
print("Races with exactly one winner:",
      int((winner_audit == 1).sum()))
print("Races with invalid winner counts:",
      int((winner_audit != 1).sum()))

print("\nRows by season:")
display(
    expanded_df.groupby("season").agg(
        driver_records=("driver_id", "size"),
        races=("round", "nunique"),
        winners=("won_race", "sum"),
        missing_grid=("starting_position_feature",
                      lambda s: s.isna().sum())
    ).reset_index()
)


============================================================
01_data_collection.ipynb — Cell 50

from pathlib import Path

PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)

# Check likely locations for the historical dataset
candidates = [
    PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv",
    PROJECT_DIR / "data" / "processed" / "history.csv",
    PROJECT_DIR / "data" / "history.csv",
]

for path in candidates:
    print(f"{'FOUND' if path.exists() else 'NOT FOUND'}: {path}")


============================================================
01_data_collection.ipynb — Cell 51

import pandas as pd

history_path = (
    PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv"
)

history = pd.read_csv(history_path)

print("History restored:", history.shape)
print("Columns:", history.columns.tolist())
print("Seasons:", sorted(history["season"].dropna().unique()))


============================================================
01_data_collection.ipynb — Cell 52

import pandas as pd
from pathlib import Path

PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)

dataset_path = (
    PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv"
)

expanded_df = pd.read_csv(dataset_path)

print("Dataset loaded successfully")
print("Shape:", expanded_df.shape)

print("\nColumns:")
print(expanded_df.columns.tolist())

print("\nSeasons available:")
print(sorted(expanded_df["season"].dropna().unique()))

print("\nRequired-column audit:")
required_columns = [
    "season",
    "round",
    "driver_id",
    "won_race",
    "grid",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

for column in required_columns:
    status = "FOUND" if column in expanded_df.columns else "MISSING"
    print(f"{status}: {column}")

if "grid" in expanded_df.columns:
    print("\nGrid missing values:", expanded_df["grid"].isna().sum())

if {"season", "round", "won_race"}.issubset(expanded_df.columns):
    winner_audit = expanded_df.groupby(["season", "round"])["won_race"].sum()
    print("\nRace groups:", len(winner_audit))
    print("Groups with exactly one winner:", int((winner_audit == 1).sum()))
    print("Groups with invalid winner counts:", int((winner_audit != 1).sum()))

print("\nRows by season:")
if "season" in expanded_df.columns:
    print(expanded_df.groupby("season").size().to_string())


============================================================
01_data_collection.ipynb — Cell 53

# Create the chronological train/test split

expanded_features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]

target = "won_race"

# Training data: 2018–2024
expanded_train = expanded_df[
    expanded_df["season"].between(2018, 2024)
].copy()

# Unseen test data: 2025
expanded_test = expanded_df[
    expanded_df["season"] == 2025
].copy()

print("Training shape:", expanded_train.shape)
print("Testing shape:", expanded_test.shape)

print("\nTraining seasons:",
      sorted(expanded_train["season"].unique()))

print("Testing seasons:",
      sorted(expanded_test["season"].unique()))

print("\nTraining rows by season:")
print(expanded_train.groupby("season").size().to_string())

print("\nTest rows by season:")
print(expanded_test.groupby("season").size().to_string())

# Validate features and target
assert all(c in expanded_df.columns for c in expanded_features)
assert expanded_train[target].notna().all()
assert expanded_test[target].notna().all()
assert expanded_train["season"].max() < expanded_test["season"].min()

print("\nChronological split created successfully.")


============================================================
01_data_collection.ipynb — Cell 61


# Read-only audit: inspect starting-position values by season
position_audit = (
    expanded_df.groupby("season")
    .agg(
        rows=("starting_position_feature", "size"),
        missing_positions=("starting_position_feature",
                           lambda s: s.isna().sum()),
        unique_positions=("starting_position_feature",
                          "nunique"),
        minimum_position=("starting_position_feature", "min"),
        maximum_position=("starting_position_feature", "max"),
    )
    .reset_index()
)

display(position_audit)

# Compare the feature against the raw grid column, if available
if "grid" in expanded_df.columns:
    print(
        "Feature equals grid:",
        expanded_df["starting_position_feature"]
        .equals(expanded_df["grid"])
    )
    display(
        expanded_df[
            ["season", "round", "driver_name",
             "grid", "starting_position_feature"]
        ].head(10)
    )
else:
    print("No raw 'grid' column exists in expanded_df.")

In [17]:

import json
from pathlib import Path

PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)

for notebook_path in (PROJECT_DIR / "notebooks").glob("*.ipynb"):
    with open(notebook_path, "r", encoding="utf-8") as file:
        notebook = json.load(file)

    for i, cell in enumerate(notebook.get("cells", [])):
        source = "".join(cell.get("source", []))
        lines = source.splitlines()

        matches = [
            j for j, line in enumerate(lines)
            if any(term in line.lower() for term in [
                "starting_position_feature",
                "expanded_model_dataset.csv",
                "to_csv("
            ])
        ]

        if matches:
            print(f"\n--- {notebook_path.name} | Cell {i} ---")
            shown = set()

            for j in matches:
                for k in range(max(0, j - 3), min(len(lines), j + 4)):
                    if k not in shown:
                        print(f"{k + 1}: {lines[k]}")
                        shown.add(k)
                print("...")

--- 01_data_collection.ipynb | Cell 0 ---
10:
11: DATA_PATH = (
12:     PROJECT_DIR / "data" / "processed"
13:     / "expanded_model_dataset.csv"
14: )
15:
16: MODEL_DIR = PROJECT_DIR / "models"
...
21:
22: # Restore the feature list
23: expanded_features = [
24:     "starting_position_feature",
25:     "driver_prior_mean_finish",
26:     "driver_prior_win_rate",
27:     "driver_recent5_mean_finish",
...

--- 01_data_collection.ipynb | Cell 7 ---
1: calendar_path = RAW_DIR / "race_calendar.csv"
2:
3: calendar_df.to_csv(calendar_path, index=False)
4:
5: print(f"Saved {len(calendar_df)} calendar entries to:")
6: print(calendar_path.resolve())
...

--- 01_data_collection.ipynb | Cell 13 ---
4: results_df.drop(
5:     columns=["position_num"],
6:     errors="ignore"
7: ).to_csv(results_path, index=False)
8:
9: print("Saved:", results_path.resolve())
...

--- 01_data_collection.ipynb | Cell 15 ---
4: results_df.drop(
5:     columns=["position_num"],
6:     errors="ignore"
7: ).to_csv(results_path, index=False)
8:
9: print("Saved to:", results_path.resolve())
...

--- 01_data_collection.ipynb | Cell 17 ---
10:     )
11:
12:     qualifying_path = RAW_DIR / "qualifying_results_partial.csv"
13:     qualifying_df.to_csv(qualifying_path, index=False)
14:
15:     print("Saved partial qualifying data:", qualifying_path.resolve())
16:     print("Rows saved:", len(qualifying_df))
...

--- 01_data_collection.ipynb | Cell 20 ---
59:     )
60:
61: season_path = RAW_DIR / f"qualifying_{season}.csv"
62: season_df.to_csv(season_path, index=False)
63:
64: print("\nSaved:", season_path.resolve())
65: print("Shape:", season_df.shape)
...

--- 01_data_collection.ipynb | Cell 21 ---
21:         )
22:
23:         save_path = RAW_DIR / "qualifying_2025_partial.csv"
24:         partial_2025.to_csv(save_path, index=False)
25:
26:         print("Saved:", save_path.resolve())
27:         print("Rows saved:", len(partial_2025))
...

--- 01_data_collection.ipynb | Cell 23 ---
114:         )
115:
116:         # Save immediately after each successful round.
117:         existing_df.to_csv(save_path, index=False)
118:         completed_rounds.add(round_number)
119:
120:         print(
...

--- 01_data_collection.ipynb | Cell 26 ---
116:         )
117:
118:         # Checkpoint after every successful round.
119:         season_df.to_csv(save_path, index=False)
120:         completed_rounds.add(round_number)
121:
122:         print(
...

--- 01_data_collection.ipynb | Cell 33 ---
137:         )
138:
139:         # Checkpoint after each successful round
140:         qualifying_df.to_csv(save_path, index=False)
141:         completed_rounds.add(round_number)
142:
143:         print(
...

--- 01_data_collection.ipynb | Cell 35 ---
32:     ).reset_index(drop=True)
33:
34:     output_path = RAW_DIR / "qualifying_2023_2025.csv"
35:     qualifying_all.to_csv(output_path, index=False)
36:
37:     print("\nCombined dataset saved:", output_path)
38:     print("Combined shape:", qualifying_all.shape)
...

--- 01_data_collection.ipynb | Cell 39 ---
52:
53: # Save the baseline dataset
54: output_path = RAW_DIR / "baseline_model_dataset.csv"
55: model_df.to_csv(output_path, index=False)
56:
57: print("Dataset saved to:", output_path)
58: print("Shape:", model_df.shape)
...

--- 01_data_collection.ipynb | Cell 44 ---
119: # Save the engineered dataset
120: output_path = RAW_DIR.parent / "processed" / "historical_model_features.csv"
121: output_path.parent.mkdir(parents=True, exist_ok=True)
122: model_features_df.to_csv(output_path, index=False)
123:
124: print("Engineered dataset saved:", output_path)
125: print("Dataset shape:", model_features_df.shape)
...

--- 01_data_collection.ipynb | Cell 49 ---
5:     history["season"].between(2018, 2025)
6: ].copy()
7:
8: expanded_df["starting_position_feature"] = pd.to_numeric(
9:     expanded_df["grid"], errors="coerce"
10: )
11:
...
12: # Keep only rows with a known starting position
13: expanded_df = expanded_df[
14:     expanded_df["starting_position_feature"].notna()
15: ].copy()
16:
17: # Define the new, consistent feature sets
...
18: grid_baseline_features = ["starting_position_feature"]
19:
20: expanded_features = [
21:     "starting_position_feature",
...
22:     "driver_prior_mean_finish",
23:     "driver_prior_win_rate",
24:     "driver_recent5_mean_finish",
...
60:         driver_records=("driver_id", "size"),
61:         races=("round", "nunique"),
62:         winners=("won_race", "sum"),
63:         missing_grid=("starting_position_feature",
64:                       lambda s: s.isna().sum())
65:     ).reset_index()
66: )
...

--- 01_data_collection.ipynb | Cell 50 ---
7:
8: # Check likely locations for the historical dataset
9: candidates = [
10:     PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv",
11:     PROJECT_DIR / "data" / "processed" / "history.csv",
12:     PROJECT_DIR / "data" / "history.csv",
13: ]
...

--- 01_data_collection.ipynb | Cell 51 ---
2: import pandas as pd
3:
4: history_path = (
5:     PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv"
6: )
7:
8: history = pd.read_csv(history_path)
...

--- 01_data_collection.ipynb | Cell 52 ---
7: )
8:
9: dataset_path = (
10:     PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv"
11: )
12:
13: expanded_df = pd.read_csv(dataset_path)
...

--- 01_data_collection.ipynb | Cell 53 ---
2: # Create the chronological train/test split
3:
4: expanded_features = [
5:     "starting_position_feature",
6:     "driver_prior_mean_finish",
7:     "driver_prior_win_rate",
8:     "driver_recent5_mean_finish",
...

--- 01_data_collection.ipynb | Cell 61 ---
4: position_audit = (
5:     expanded_df.groupby("season")
6:     .agg(
7:         rows=("starting_position_feature", "size"),
8:         missing_positions=("starting_position_feature",
9:                            lambda s: s.isna().sum()),
10:         unique_positions=("starting_position_feature",
...
11:                           "nunique"),
...
12:         minimum_position=("starting_position_feature", "min"),
13:         maximum_position=("starting_position_feature", "max"),
...
14:     )
15:     .reset_index()
...
16: )
...
21: if "grid" in expanded_df.columns:
22:     print(
23:         "Feature equals grid:",
24:         expanded_df["starting_position_feature"]
25:         .equals(expanded_df["grid"])
26:     )
27:     display(
...
28:         expanded_df[
29:             ["season", "round", "driver_name",
30:              "grid", "starting_position_feature"]
31:         ].head(10)
32:     )
33: else:
...

--- 02_model_recovery_fixed.ipynb | Cell 1 ---
12: from sklearn.ensemble import RandomForestClassifier
13:
14: PROJECT_DIR = Path(r"C:\Users\saksham\Desktop\Project\f1-prediction-platform")
15: DATA_PATH = PROJECT_DIR / "data" / "processed" / "expanded_model_dataset.csv"
16: MODEL_DIR = PROJECT_DIR / "models"
17: REPORT_DIR = PROJECT_DIR / "reports"
18:
...
32:
33: if not DATA_PATH.exists():
34:     raise FileNotFoundError(
35:         "expanded_model_dataset.csv was not found. Do not recollect data yet; "
36:         "check the project's data/processed folder."
37:     )
...

--- 02_model_recovery_fixed.ipynb | Cell 2 ---
2: expanded_df = pd.read_csv(DATA_PATH)
3:
4: expanded_features = [
5:     "starting_position_feature",
6:     "driver_prior_mean_finish",
7:     "driver_prior_win_rate",
8:     "driver_recent5_mean_finish",
...
9:     "constructor_prior_mean_finish",
10:     "constructor_prior_win_rate",
11: ]
12: baseline_features = ["starting_position_feature"]
13: target = "won_race"
14:
15: required_columns = [
...

--- 02_model_recovery_fixed.ipynb | Cell 4 ---
2: test_predictions = expanded_test[
3:     [
4:         "season", "round", "race_name", "driver_id", "driver_name",
5:         "constructor_name", "grid", "starting_position_feature", target
6:     ]
7: ].copy()
8:
...
50:
51: prediction_path = REPORT_DIR / "predictions_2025_rebuilt.csv"
52: comparison_path = REPORT_DIR / "model_comparison_2025_rebuilt.csv"
53: test_predictions.to_csv(prediction_path, index=False)
54: model_comparison.to_csv(comparison_path, index=False)
55:
56: print("Saved predictions:", prediction_path)
...
57: print("Saved model comparison:", comparison_path)
...

--- 02_model_recovery_fixed.ipynb | Cell 6 ---
63: probability_path = REPORT_DIR / "race_level_probabilities_2025_normalized.csv"
64: metrics_path = REPORT_DIR / "probability_evaluation_2025_normalized.csv"
65:
66: normalized_predictions.to_csv(probability_path, index=False)
67: model_metrics.to_csv(metrics_path, index=False)
68:
69: print("Saved race-level probabilities:", probability_path)
...
70: print("Saved probability evaluation:", metrics_path)
...

--- 03_chronological_validation.ipynb | Cell 0 ---
9: if PROJECT_ROOT.name == "notebooks":
10:     PROJECT_ROOT = PROJECT_ROOT.parent
11:
12: DATA_PATH = PROJECT_ROOT / "data" / "processed" / "expanded_model_dataset.csv"
13:
14: # Load the existing dataset
15: df = pd.read_csv(DATA_PATH)
...

--- 03_chronological_validation.ipynb | Cell 1 ---
25:
26: # Check missing values in our intended features
27: candidate_features = [
28:     "starting_position_feature",
29:     "driver_prior_mean_finish",
30:     "driver_prior_win_rate",
31:     "driver_recent5_mean_finish",
...

--- 03_chronological_validation.ipynb | Cell 4 ---
9: from sklearn.dummy import DummyClassifier
10:
11: features = [
12:     "starting_position_feature",
13:     "driver_prior_mean_finish",
14:     "driver_prior_win_rate",
15:     "driver_recent5_mean_finish",
...

--- 03_chronological_validation.ipynb | Cell 5 ---
11: results = []
12:
13: # Baseline: starting position only
14: baseline_features = ["starting_position_feature"]
15:
16: # Compare baseline, Logistic Regression, and Random Forest
17: for train_end, test_season in validation_splits:
...

--- 03_chronological_validation.ipynb | Cell 6 ---
22:
23:     models = {
24:         "Baseline": (
25:             ["starting_position_feature"],
26:             Pipeline([
27:                 ("imputer", SimpleImputer(strategy="median")),
28:                 ("scaler", StandardScaler()),
...

--- 03_chronological_validation.ipynb | Cell 7 ---
2: # Step 5: Audit feature availability and missing values
3:
4: feature_columns = [
5:     "starting_position_feature",
6:     "driver_prior_mean_finish",
7:     "driver_prior_win_rate",
8:     "driver_recent5_mean_finish",
...

--- 03_chronological_validation.ipynb | Cell 8 ---
10: notebooks_dir = PROJECT_DIR / "notebooks"
11:
12: search_terms = [
13:     "starting_position_feature",
14:     "expanded_model_dataset.csv",
15: ]
16:
...
17: if not notebooks_dir.exists():
...

--- 03_chronological_validation.ipynb | Cell 9 ---
22:         source = "".join(cell.get("source", []))
23:
24:         if (
25:             "starting_position_feature" in source
26:             or "expanded_model_dataset.csv" in source
27:         ):
28:             print(f"\n{'=' * 60}")
...
29:             print(f"{notebook_name} — Cell {i}")
...

--- 03_chronological_validation.ipynb | Cell 10 ---
17:         matches = [
18:             j for j, line in enumerate(lines)
19:             if any(term in line.lower() for term in [
20:                 "starting_position_feature",
21:                 "expanded_model_dataset.csv",
22:                 "to_csv("
23:             ])
...
24:         ]
...
25:
...

In [19]:

from pathlib import Path
import pandas as pd

# Load the existing dataset directly
PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)
DATA_PATH = (
    PROJECT_DIR / "data" / "processed"
    / "expanded_model_dataset.csv"
)

expanded_df = pd.read_csv(DATA_PATH)

# Compare starting-position feature against grid
comparison = expanded_df[
    ["season", "round", "driver_name", "grid",
     "starting_position_feature"]
].copy()

comparison["grid"] = pd.to_numeric(
    comparison["grid"], errors="coerce"
)
comparison["starting_position_feature"] = pd.to_numeric(
    comparison["starting_position_feature"], errors="coerce"
)

different_rows = comparison[
    comparison["grid"].ne(
        comparison["starting_position_feature"]
    )
    | comparison["grid"].isna()
    | comparison["starting_position_feature"].isna()
]

print("Dataset loaded:", expanded_df.shape)
print("Total rows:", len(comparison))
print("Rows with differences or missing values:", len(different_rows))

display(different_rows.head(25))

Dataset loaded: (3458, 27)
Total rows: 3458
Rows with differences or missing values: 45

      season  round         driver_name  grid  starting_position_feature
182     2018     10     Brendon Hartley     0                        NaN
460     2019      3     Alexander Albon     0                        NaN
482     2019      4        Pierre Gasly     0                        NaN
488     2019      4       Robert Kubica     0                        NaN
494     2019      4      Kimi Räikkönen     0                        NaN
506     2019      5     Nico Hülkenberg     0                        NaN
547     2019      7     Kevin Magnussen     0                        NaN
596     2019      9      George Russell     0                        NaN
668     2019     13       Robert Kubica     0                        NaN
694     2019     14      Kimi Räikkönen     0                        NaN
720     2019     16     Alexander Albon     0                        NaN
748     2019     17       Robert Kubica     0                        NaN
793     2019     19        Sergio Pérez     0                        NaN
864     2020      2     Romain Grosjean     0                        NaN
884     2020      3     Romain Grosjean     0                        NaN
886     2020      3     Kevin Magnussen     0                        NaN
1108    2020     14     Nicholas Latifi     0                        NaN
1116    2020     14      George Russell     0                        NaN
1192    2021      1        Sergio Pérez     0                        NaN
1219    2021      2    Sebastian Vettel     0                        NaN
1318    2021      7        Yuki Tsunoda     0                        NaN
1372    2021     10        Sergio Pérez     0                        NaN
1383    2021     11  Antonio Giovinazzi     0                        NaN
1412    2021     12        Sergio Pérez     0                        NaN
1413    2021     12      Kimi Räikkönen     0                        NaN

In [20]:

# Summarize the mismatches without changing any data
print("Mismatch patterns:")
display(
    different_rows.groupby(
        ["grid", "starting_position_feature"],
        dropna=False
    ).size().reset_index(name="count")
)

print(
    "\nRows where grid is zero:",
    (expanded_df["grid"] == 0).sum()
)

print(
    "Rows where starting_position_feature is missing:",
    expanded_df["starting_position_feature"].isna().sum()
)

Mismatch patterns:

   grid  starting_position_feature  count
0     0                        NaN     45

Rows where grid is zero: 45
Rows where starting_position_feature is missing: 45

In [21]:

import joblib
from pathlib import Path

PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)
MODEL_DIR = PROJECT_DIR / "models"

model_files = [
    "baseline_model.joblib",
    "logistic_regression_model.joblib",
    "random_forest_model.joblib",
]

for filename in model_files:
    model = joblib.load(MODEL_DIR / filename)

    print(f"\n{filename}")
    print("Model type:", type(model).__name__)

    if hasattr(model, "named_steps"):
        print("Pipeline steps:", list(model.named_steps.keys()))
        for step_name, step in model.named_steps.items():
            print(f"  {step_name}: {type(step).__name__}")

baseline_model.joblib
Model type: Pipeline
Pipeline steps: ['imputer', 'scaler', 'classifier']
  imputer: SimpleImputer
  scaler: StandardScaler
  classifier: LogisticRegression

logistic_regression_model.joblib
Model type: Pipeline
Pipeline steps: ['imputer', 'scaler', 'classifier']
  imputer: SimpleImputer
  scaler: StandardScaler
  classifier: LogisticRegression

random_forest_model.joblib
Model type: Pipeline
Pipeline steps: ['imputer', 'classifier']
  imputer: SimpleImputer
  classifier: RandomForestClassifier

In [22]:

import joblib
from pathlib import Path

PROJECT_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform"
)
MODEL_DIR = PROJECT_DIR / "models"

model_files = [
    "baseline_model.joblib",
    "logistic_regression_model.joblib",
    "random_forest_model.joblib",
]

for filename in model_files:
    model = joblib.load(MODEL_DIR / filename)

    print(f"\n{'=' * 55}")
    print(filename)

    imputer = model.named_steps["imputer"]
    print("Imputer strategy:", imputer.strategy)
    print("Missing-value indicator:", imputer.add_indicator)

    if hasattr(imputer, "statistics_"):
        print("Imputer statistics:", imputer.statistics_)

=======================================================
baseline_model.joblib
Imputer strategy: median
Missing-value indicator: False
Imputer statistics: [10.]

=======================================================
logistic_regression_model.joblib
Imputer strategy: median
Missing-value indicator: False
Imputer statistics: [10.         10.76923077  0.         11.         11.125       0.        ]

=======================================================
random_forest_model.joblib
Imputer strategy: median
Missing-value indicator: False
Imputer statistics: [10.         10.76923077  0.         11.         11.125       0.        ]

In [23]:

# Read-only checks before chronological validation

print("Rows:", len(expanded_df))
print("Seasons:", sorted(expanded_df["season"].unique()))

race_winner_check = (
    expanded_df.groupby(["season", "round"])["won_race"]
    .agg(runners="size", winners="sum")
    .reset_index()
)

print("\nRace count:", len(race_winner_check))
print(
    "Races with exactly one winner:",
    (race_winner_check["winners"] == 1).sum(),
)
print(
    "Races with zero or multiple winners:",
    (race_winner_check["winners"] != 1).sum(),
)

display(
    race_winner_check[
        race_winner_check["winners"] != 1
    ].head(20)
)

Rows: 3458
Seasons: [np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

Race count: 173
Races with exactly one winner: 173
Races with zero or multiple winners: 0

Empty DataFrame
Columns: [season, round, runners, winners]
Index: []

In [24]:

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.metrics import log_loss, brier_score_loss
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# Features and target already used in the project
features = [
    "starting_position_feature",
    "driver_prior_mean_finish",
    "driver_prior_win_rate",
    "driver_recent5_mean_finish",
    "constructor_prior_mean_finish",
    "constructor_prior_win_rate",
]
target = "won_race"

# Evaluate each season using only earlier seasons for training
results = []

for test_season in range(2021, 2026):
    train = expanded_df[expanded_df["season"] < test_season].copy()
    test = expanded_df[expanded_df["season"] == test_season].copy()

    X_train = train[features]
    y_train = train[target].astype(int)
    X_test = test[features]
    y_test = test[target].astype(int)

    models = {
        "Logistic Regression": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("classifier", LogisticRegression(
                max_iter=2000, class_weight="balanced"
            )),
        ]),
        "Random Forest": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("classifier", RandomForestClassifier(
                n_estimators=300,
                random_state=42,
                class_weight="balanced",
                n_jobs=-1,
            )),
        ]),
    }

    # Baseline: starting position only
    baseline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(
            max_iter=2000, class_weight="balanced"
        )),
    ])
    models["Baseline"] = baseline

    for model_name, model in models.items():
        selected_features = (
            ["starting_position_feature"]
            if model_name == "Baseline"
            else features
        )

        model.fit(train[selected_features], y_train)
        probabilities = model.predict_proba(
            test[selected_features]
        )[:, 1]

        # Normalize driver winner scores within each race
        race_results = test[
            ["season", "round", target]
        ].copy()
        race_results["probability"] = probabilities

        race_results["race_probability"] = (
            race_results.groupby(["season", "round"])["probability"]
            .transform(
                lambda s: s / s.sum() if s.sum() > 0 else 1 / len(s)
            )
        )

        # Top-1 winner accuracy: did the highest-scored driver win?
        race_winners = race_results.loc[
            race_results.groupby(["season", "round"])["race_probability"]
            .idxmax()
        ]
        top1_accuracy = race_winners[target].mean()

        # Race-level multiclass log loss and Brier score
        race_log_losses = []
        race_brier_scores = []

        for _, group in race_results.groupby(["season", "round"]):
            y_race = group[target].to_numpy()
            p_race = group["race_probability"].to_numpy()
            p_race = np.clip(p_race, 1e-15, 1)
            p_race = p_race / p_race.sum()

            race_log_losses.append(
                -np.sum(y_race * np.log(p_race))
            )
            race_brier_scores.append(
                np.sum((p_race - y_race) ** 2)
            )

        results.append({
            "test_season": test_season,
            "model": model_name,
            "training_seasons": f"2018–{test_season - 1}",
            "races": test[["season", "round"]].drop_duplicates().shape[0],
            "top1_winner_accuracy": top1_accuracy,
            "mean_race_log_loss": np.mean(race_log_losses),
            "mean_race_brier_score": np.mean(race_brier_scores),
        })

validation_results = pd.DataFrame(results)

display(
    validation_results.sort_values(
        ["test_season", "mean_race_log_loss"]
    ).round(4)
)

,test_season,model,training_seasons,races,top1_winner_accuracy,mean_race_log_loss,mean_race_brier_score
1,2021,Random Forest,2018–2020,22,0.2727,1.7520,0.7827
0,2021,Logistic Regression,2018–2020,22,0.3636,1.7524,0.7586
2,2021,Baseline,2018–2020,22,0.5000,1.9412,0.8097
4,2022,Random Forest,2018–2021,22,0.2273,1.8047,0.9221
3,2022,Logistic Regression,2018–2021,22,0.4091,1.8427,0.7956
5,2022,Baseline,2018–2021,22,0.4545,2.1103,0.8222
7,2023,Random Forest,2018–2022,22,0.6818,0.8371,0.4172
6,2023,Logistic Regression,2018–2022,22,0.7273,1.5517,0.7124
8,2023,Baseline,2018–2022,22,0.6364,1.9172,0.8100
9,2024,Logistic Regression,2018–2023,24,0.4583,1.7693,0.7834
11,2024,Baseline,2018–2023,24,0.4583,2.0376,0.8088
10,2024,Random Forest,2018–2023,24,0.4583,2.7682,0.6973
13,2025,Random Forest,2018–2024,24,0.4583,1.3528,0.6573
12,2025,Logistic Regression,2018–2024,24,0.5000,1.6348,0.7558
14,2025,Baseline,2018–2024,24,0.6667,1.7835,0.7853

In [25]:

# Diagnostic: compare baseline predictions with actual pole-sitter wins

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import pandas as pd

baseline_features = ["starting_position_feature"]
diagnostics = []

for season in range(2021, 2026):
    train = expanded_df[expanded_df["season"] < season].copy()
    test = expanded_df[expanded_df["season"] == season].copy()

    baseline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(
            max_iter=2000,
            class_weight="balanced"
        )),
    ])

    baseline.fit(train[baseline_features], train["won_race"])
    test = test.copy()
    test["baseline_probability"] = baseline.predict_proba(
        test[baseline_features]
    )[:, 1]

    # Select the highest-scoring driver in each race
    picks = test.loc[
        test.groupby(["season", "round"])["baseline_probability"].idxmax()
    ]

    # Actual wins by drivers who started from grid position 1
    grid_numeric = pd.to_numeric(test["grid"], errors="coerce")
    pole_rows = test[grid_numeric == 1]

    diagnostics.append({
        "season": season,
        "races": test["round"].nunique(),
        "baseline_correct_picks": int(picks["won_race"].sum()),
        "baseline_accuracy": picks["won_race"].mean(),
        "pole_sitter_actual_wins": int(pole_rows["won_race"].sum()),
        "baseline_picks_match_pole": bool(
            set(picks.index) == set(pole_rows.index)
        ) if len(picks) == len(pole_rows) else False,
    })

display(pd.DataFrame(diagnostics).round(4))

,season,races,baseline_correct_picks,baseline_accuracy,pole_sitter_actual_wins,baseline_picks_match_pole
0,2021,22,11,0.5000,11,True
1,2022,22,10,0.4545,10,True
2,2023,22,14,0.6364,14,True
3,2024,24,11,0.4583,11,True
4,2025,24,16,0.6667,16,True

In [26]:

from pathlib import Path
import pandas as pd

PROJECT_DIR = Path(r"C:\Users\saksham\Desktop\Project\f1-prediction-platform")
REPORTS_DIR = PROJECT_DIR / "reports"

files_to_check = [
    "model_comparison_2025_rebuilt.csv",
    "model_comparison_2025.csv",
    "probability_evaluation_2025_normalized.csv",
    "probability_evaluation_2025.csv",
    "normalized_summary.csv",
    "model metrics.csv",
    "normalized metrics.csv",
]

for filename in files_to_check:
    filepath = REPORTS_DIR / filename

    if filepath.exists():
        df = pd.read_csv(filepath)
        print(f"\n{'=' * 70}")
        print(f"FILE: {filename}")
        print(f"Shape: {df.shape}")
        print("Columns:", df.columns.tolist())
        display(df.head(5))
    else:
        print(f"\nNot found: {filename}")

======================================================================
FILE: model_comparison_2025_rebuilt.csv
Shape: (3, 6)
Columns: ['model', 'races_evaluated', 'top1_correct', 'top1_accuracy_pct', 'winner_in_top3_pct', 'mean_actual_winner_rank']

,model,races_evaluated,top1_correct,top1_accuracy_pct,winner_in_top3_pct,mean_actual_winner_rank
0,Starting-grid baseline,24,16,66.67,95.83,1.54
1,Logistic Regression + history,24,12,50.00,100.00,1.67
2,Random Forest + history,24,14,58.33,87.50,1.79

======================================================================
FILE: model_comparison_2025.csv
Shape: (3, 6)
Columns: ['model', 'races', 'correct_winners', 'top1_accuracy_pct', 'winner_in_top3_pct', 'mean_winner_rank']

,model,races,correct_winners,top1_accuracy_pct,winner_in_top3_pct,mean_winner_rank
0,Baseline: starting grid,24,16,66.67,95.83,1.54
1,Logistic regression + history,24,12,50.00,100.00,1.67
2,Random Forest + history,24,14,58.33,87.50,1.79

======================================================================
FILE: probability_evaluation_2025_normalized.csv
Shape: (4, 5)
Columns: ['model', 'races_evaluated', 'mean_log_loss', 'mean_brier_score', 'mean_winner_probability']

,model,races_evaluated,mean_log_loss,mean_brier_score,mean_winner_probability
0,Logistic Regression,24,1.1693,0.5980,0.3442
1,Baseline,24,1.2254,0.6138,0.3114
2,Random Forest,24,1.3708,0.6585,0.2878
3,Uniform baseline,24,2.9936,0.9499,0.0501

======================================================================
FILE: probability_evaluation_2025.csv
Shape: (4, 5)
Columns: ['model', 'races_evaluated', 'mean_log_loss', 'mean_brier_score', 'mean_winner_probability']

,model,races_evaluated,mean_log_loss,mean_brier_score,mean_winner_probability
0,Baseline,24,2.737363,0.920696,0.064998
1,Logistic Regression,24,2.701290,0.915369,0.067818
2,Random Forest,24,2.697920,0.914387,0.068398
3,Uniform baseline,24,2.993595,0.949890,0.050110

======================================================================
FILE: normalized_summary.csv
Shape: (3, 3)
Columns: ['mean_log_loss', 'mean_brier_score', 'mean_winner_probability']

   mean_log_loss  mean_brier_score  mean_winner_probability
0         1.1693            0.5980                   0.3442
1         1.2254            0.6138                   0.3114
2         1.3708            0.6585                   0.2878

Not found: model metrics.csv

Not found: normalized metrics.csv

In [27]:

from pathlib import Path
import pandas as pd

REPORTS_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform\reports"
)

for filename in [
    "predictions_2025_rebuilt.csv",
    "predictions_2025.csv",
    "race_level_probabilities_2025_normalized.csv",
    "race_level_probabilities_2025.csv",
]:
    path = REPORTS_DIR / filename

    if path.exists():
        df = pd.read_csv(path)
        print(f"\n{'=' * 60}\n{filename}")
        print("Shape:", df.shape)
        print("Columns:", df.columns.tolist())
        display(df.head(3))
    else:
        print(f"\nMissing file: {filename}")

============================================================
predictions_2025_rebuilt.csv
Shape: (479, 15)
Columns: ['season', 'round', 'race_name', 'driver_id', 'driver_name', 'constructor_name', 'grid', 'starting_position_feature', 'won_race', 'baseline_score', 'logistic_score', 'random_forest_score', 'baseline_rank', 'logistic_rank', 'rf_rank']

,season,round,race_name,driver_id,driver_name,constructor_name,grid,starting_position_feature,won_race,baseline_score,logistic_score,random_forest_score,baseline_rank,logistic_rank,rf_rank
0,2025,1,Australian Grand Prix,albon,Alexander Albon,Williams,6,6.0,0,0.032194,0.002932,0.022717,6,10,7
1,2025,1,Australian Grand Prix,alonso,Fernando Alonso,Aston Martin,12,12.0,0,0.001062,0.000928,0.000179,12,12,17
2,2025,1,Australian Grand Prix,antonelli,Andrea Kimi Antonelli,Mercedes,16,16.0,0,0.000107,0.000122,0.006285,16,16,11

============================================================
predictions_2025.csv
Shape: (479, 14)
Columns: ['season', 'round', 'race_name', 'driver_id', 'driver_name', 'constructor_name', 'grid', 'won_race', 'baseline_score', 'logistic_score', 'random_forest_score', 'baseline_rank', 'logistic_rank', 'rf_rank']

,season,round,race_name,driver_id,driver_name,constructor_name,grid,won_race,baseline_score,logistic_score,random_forest_score,baseline_rank,logistic_rank,rf_rank
0,2025,1,Australian Grand Prix,albon,Alexander Albon,Williams,6,0,0.032194,0.002932,0.022717,6.0,10.0,7.0
1,2025,1,Australian Grand Prix,alonso,Fernando Alonso,Aston Martin,12,0,0.001062,0.000928,0.000179,12.0,12.0,17.0
2,2025,1,Australian Grand Prix,antonelli,Andrea Kimi Antonelli,Mercedes,16,0,0.000107,0.000122,0.006285,16.0,16.0,11.0

============================================================
race_level_probabilities_2025_normalized.csv
Shape: (479, 18)
Columns: ['season', 'round', 'race_name', 'driver_id', 'driver_name', 'constructor_name', 'grid', 'starting_position_feature', 'won_race', 'baseline_score', 'logistic_score', 'random_forest_score', 'baseline_rank', 'logistic_rank', 'rf_rank', 'baseline_normalized_probability', 'logistic_normalized_probability', 'rf_normalized_probability']

,season,round,race_name,driver_id,driver_name,constructor_name,grid,starting_position_feature,won_race,baseline_score,logistic_score,random_forest_score,baseline_rank,logistic_rank,rf_rank,baseline_normalized_probability,logistic_normalized_probability,rf_normalized_probability
0,2025,1,Australian Grand Prix,albon,Alexander Albon,Williams,6,6.0,0,0.032194,0.002932,0.022717,6,10,7,0.032193,0.003095,0.019746
1,2025,1,Australian Grand Prix,alonso,Fernando Alonso,Aston Martin,12,12.0,0,0.001062,0.000928,0.000179,12,12,17,0.001062,0.000979,0.000155
2,2025,1,Australian Grand Prix,antonelli,Andrea Kimi Antonelli,Mercedes,16,16.0,0,0.000107,0.000122,0.006285,16,16,11,0.000107,0.000129,0.005463

============================================================
race_level_probabilities_2025.csv
Shape: (479, 17)
Columns: ['season', 'round', 'race_name', 'driver_id', 'driver_name', 'constructor_name', 'grid', 'won_race', 'baseline_score', 'logistic_score', 'random_forest_score', 'baseline_rank', 'logistic_rank', 'rf_rank', 'baseline_win_probability', 'logistic_win_probability', 'rf_win_probability']

,season,round,race_name,driver_id,driver_name,constructor_name,grid,won_race,baseline_score,logistic_score,random_forest_score,baseline_rank,logistic_rank,rf_rank,baseline_win_probability,logistic_win_probability,rf_win_probability
0,2025,1,Australian Grand Prix,albon,Alexander Albon,Williams,6,0,0.032194,0.002932,0.022717,6.0,10.0,7.0,0.048872,0.047610,0.048009
1,2025,1,Australian Grand Prix,alonso,Fernando Alonso,Aston Martin,12,0,0.001062,0.000928,0.000179,12.0,12.0,17.0,0.047374,0.047515,0.046939
2,2025,1,Australian Grand Prix,antonelli,Andrea Kimi Antonelli,Mercedes,16,0,0.000107,0.000122,0.006285,16.0,16.0,11.0,0.047329,0.047477,0.047227

In [28]:

from pathlib import Path
import pandas as pd

REPORTS_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform\reports"
)

files = {
    "normalized": (
        "race_level_probabilities_2025_normalized.csv",
        [
            "baseline_normalized_probability",
            "logistic_normalized_probability",
            "rf_normalized_probability",
        ],
    ),
    "older": (
        "race_level_probabilities_2025.csv",
        [
            "baseline_win_probability",
            "logistic_win_probability",
            "rf_win_probability",
        ],
    ),
}

for label, (filename, probability_columns) in files.items():
    path = REPORTS_DIR / filename
    df = pd.read_csv(path)

    print(f"\n{'=' * 60}")
    print(f"{label.upper()} FILE: {filename}")

    for column in probability_columns:
        if column not in df.columns:
            print(f"{column}: column missing")
            continue

        race_sums = df.groupby(
            ["season", "round", "race_name"]
        )[column].sum(min_count=1)

        print(f"\n{column}")
        print("Race probability sums — first 5:")
        print(race_sums.head().round(6).to_string())
        print("Minimum race sum:", round(race_sums.min(), 6))
        print("Maximum race sum:", round(race_sums.max(), 6))
        print("Races summing to 1 (tolerance 0.001):",
              int(((race_sums - 1).abs() <= 0.001).sum()),
              "of", len(race_sums))

============================================================
NORMALIZED FILE: race_level_probabilities_2025_normalized.csv

baseline_normalized_probability
Race probability sums — first 5:
season  round  race_name
2025    1      Australian Grand Prix       1.0
        2      Chinese Grand Prix          1.0
        3      Japanese Grand Prix         1.0
        4      Bahrain Grand Prix          1.0
        5      Saudi Arabian Grand Prix    1.0
Minimum race sum: 1.0
Maximum race sum: 1.0
Races summing to 1 (tolerance 0.001): 24 of 24

logistic_normalized_probability
Race probability sums — first 5:
season  round  race_name
2025    1      Australian Grand Prix       1.0
        2      Chinese Grand Prix          1.0
        3      Japanese Grand Prix         1.0
        4      Bahrain Grand Prix          1.0
        5      Saudi Arabian Grand Prix    1.0
Minimum race sum: 1.0
Maximum race sum: 1.0
Races summing to 1 (tolerance 0.001): 24 of 24

rf_normalized_probability
Race probability sums — first 5:
season  round  race_name
2025    1      Australian Grand Prix       1.0
        2      Chinese Grand Prix          1.0
        3      Japanese Grand Prix         1.0
        4      Bahrain Grand Prix          1.0
        5      Saudi Arabian Grand Prix    1.0
Minimum race sum: 1.0
Maximum race sum: 1.0
Races summing to 1 (tolerance 0.001): 24 of 24

============================================================
OLDER FILE: race_level_probabilities_2025.csv

baseline_win_probability
Race probability sums — first 5:
season  round  race_name
2025    1      Australian Grand Prix       1.0
        2      Chinese Grand Prix          1.0
        3      Japanese Grand Prix         1.0
        4      Bahrain Grand Prix          1.0
        5      Saudi Arabian Grand Prix    1.0
Minimum race sum: 1.0
Maximum race sum: 1.0
Races summing to 1 (tolerance 0.001): 24 of 24

logistic_win_probability
Race probability sums — first 5:
season  round  race_name
2025    1      Australian Grand Prix       1.0
        2      Chinese Grand Prix          1.0
        3      Japanese Grand Prix         1.0
        4      Bahrain Grand Prix          1.0
        5      Saudi Arabian Grand Prix    1.0
Minimum race sum: 1.0
Maximum race sum: 1.0
Races summing to 1 (tolerance 0.001): 24 of 24

rf_win_probability
Race probability sums — first 5:
season  round  race_name
2025    1      Australian Grand Prix       1.0
        2      Chinese Grand Prix          1.0
        3      Japanese Grand Prix         1.0
        4      Bahrain Grand Prix          1.0
        5      Saudi Arabian Grand Prix    1.0
Minimum race sum: 1.0
Maximum race sum: 1.0
Races summing to 1 (tolerance 0.001): 24 of 24

In [29]:

from pathlib import Path
import pandas as pd

REPORTS_DIR = Path(
    r"C:\Users\saksham\Desktop\Project\f1-prediction-platform\reports"
)

df = pd.read_csv(
    REPORTS_DIR / "race_level_probabilities_2025_normalized.csv"
)

# Inspect the first 5 races and each model's top-ranked driver.
probability_columns = {
    "Baseline": ("baseline_normalized_probability", "baseline_rank"),
    "Logistic Regression": ("logistic_normalized_probability", "logistic_rank"),
    "Random Forest": ("rf_normalized_probability", "rf_rank"),
}

for (season, rnd, race_name), race in df.groupby(
    ["season", "round", "race_name"], sort=True
):
    if rnd > 5:
        break

    winners = race[race["won_race"] == 1]
    print(f"\n{rnd}. {race_name}")

    if winners.empty:
        print("Winner label missing; skipping.")
        continue

    print("Actual winner:", winners.iloc[0]["driver_name"])

    for model, (prob_col, rank_col) in probability_columns.items():
        top = race.sort_values(rank_col).iloc[0]
        winner = winners.iloc[0]

        print(
            f"  {model}: predicts {top['driver_name']} "
            f"({top[prob_col]:.1%}); "
            f"actual winner probability = {winner[prob_col]:.1%}"
        )

1. Australian Grand Prix
Actual winner: Lando Norris
  Baseline: predicts Lando Norris (37.0%); actual winner probability = 37.0%
  Logistic Regression: predicts Max Verstappen (34.3%); actual winner probability = 29.9%
  Random Forest: predicts Lando Norris (33.2%); actual winner probability = 33.2%

2. Chinese Grand Prix
Actual winner: Oscar Piastri
  Baseline: predicts Oscar Piastri (37.0%); actual winner probability = 37.0%
  Logistic Regression: predicts Max Verstappen (29.0%); actual winner probability = 19.0%
  Random Forest: predicts Max Verstappen (26.0%); actual winner probability = 21.9%

3. Japanese Grand Prix
Actual winner: Max Verstappen
  Baseline: predicts Max Verstappen (37.0%); actual winner probability = 37.0%
  Logistic Regression: predicts Max Verstappen (47.3%); actual winner probability = 47.3%
  Random Forest: predicts Max Verstappen (40.6%); actual winner probability = 40.6%

4. Bahrain Grand Prix
Actual winner: Oscar Piastri
  Baseline: predicts Oscar Piastri (37.0%); actual winner probability = 37.0%
  Logistic Regression: predicts Oscar Piastri (35.6%); actual winner probability = 35.6%
  Random Forest: predicts Oscar Piastri (26.1%); actual winner probability = 26.1%

5. Saudi Arabian Grand Prix
Actual winner: Oscar Piastri
  Baseline: predicts Max Verstappen (37.0%); actual winner probability = 24.8%
  Logistic Regression: predicts Max Verstappen (49.4%); actual winner probability = 23.5%
  Random Forest: predicts Max Verstappen (39.8%); actual winner probability = 18.0%